import type { ReportDataSet } from "./types.js";

export const reportsMockDataSet = {
  context: {
    tenantId: "tenant-demo",
    financialProfileId: "profile-personal-demo",
  },
  period: {
    startsOn: "2026-06-01",
    endsOn: "2026-06-30",
    label: "Junho de 2026",
  },
  filters: {
    startsOn: "2026-06-01",
    endsOn: "2026-06-30",
  },
  categories: [
    {
      id: "category-income-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Receitas",
      type: "income",
      status: "active",
    },
    {
      id: "category-home-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Moradia",
      type: "expense",
      status: "active",
    },
    {
      id: "category-food-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Alimentacao",
      type: "expense",
      status: "active",
    },
    {
      id: "category-market-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Mercado",
      type: "expense",
      status: "active",
      parentCategoryId: "category-food-demo",
    },
    {
      id: "category-card-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Cartao",
      type: "expense",
      status: "active",
    },
    {
      id: "category-education-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Educacao",
      type: "expense",
      status: "active",
    },
    {
      id: "category-old-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Categoria antiga demo",
      type: "expense",
      status: "archived",
    },
  ],
  budgets: [
    {
      id: "budget-food-june",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      categoryId: "category-food-demo",
      categoryName: "Alimentacao",
      startsOn: "2026-06-01",
      endsOn: "2026-06-30",
      plannedAmountInCents: 120000,
    },
    {
      id: "budget-home-june",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      categoryId: "category-home-demo",
      categoryName: "Moradia",
      startsOn: "2026-06-01",
      endsOn: "2026-06-30",
      plannedAmountInCents: 180000,
    },
    {
      id: "budget-card-june",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      categoryId: "category-card-demo",
      categoryName: "Cartao",
      startsOn: "2026-06-01",
      endsOn: "2026-06-30",
      plannedAmountInCents: 50000,
    },
    {
      id: "budget-education-june",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      categoryId: "category-education-demo",
      categoryName: "Educacao",
      startsOn: "2026-06-01",
      endsOn: "2026-06-30",
      plannedAmountInCents: 30000,
    },
    {
      id: "budget-foreign-june",
      tenantId: "tenant-outro",
      financialProfileId: "profile-outro",
      categoryId: "category-foreign-demo",
      categoryName: "Ignorar",
      startsOn: "2026-06-01",
      endsOn: "2026-06-30",
      plannedAmountInCents: 999999,
    },
  ],
  transactions: [
    {
      id: "report-income-may-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-05-05",
      description: "Receita maio demo",
      type: "income",
      status: "posted",
      amountInCents: 600000,
      accountId: "account-checking-demo",
      categoryId: "category-income-demo",
    },
    {
      id: "report-expense-may-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-05-12",
      description: "Despesas maio demo",
      type: "expense",
      status: "posted",
      amountInCents: 330000,
      accountId: "account-checking-demo",
      categoryId: "category-home-demo",
    },
    {
      id: "report-income-june-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-05",
      description: "Receita mensal demo",
      type: "income",
      status: "posted",
      amountInCents: 620000,
      accountId: "account-checking-demo",
      categoryId: "category-income-demo",
    },
    {
      id: "report-expense-home-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-07",
      description: "Moradia demo",
      type: "expense",
      status: "posted",
      amountInCents: 180000,
      accountId: "account-checking-demo",
      categoryId: "category-home-demo",
    },
    {
      id: "report-expense-market-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-09",
      description: "Mercado demo",
      type: "expense",
      status: "posted",
      amountInCents: 95000,
      accountId: "account-checking-demo",
      categoryId: "category-market-demo",
    },
    {
      id: "report-transfer-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-11",
      description: "Reserva demo",
      type: "transfer",
      status: "posted",
      amountInCents: 50000,
      accountId: "account-checking-demo",
      destinationAccountId: "account-savings-demo",
    },
    {
      id: "report-expense-card-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-16",
      description: "Fatura demo",
      type: "expense",
      status: "scheduled",
      amountInCents: 62750,
      accountId: "account-checking-demo",
      categoryId: "category-card-demo",
    },
    {
      id: "report-archived-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-18",
      description: "Lancamento arquivado demo",
      type: "expense",
      status: "archived",
      amountInCents: 1200,
      accountId: "account-checking-demo",
      categoryId: "category-old-demo",
    },
    {
      id: "report-income-july-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-07-05",
      description: "Receita julho demo",
      type: "income",
      status: "posted",
      amountInCents: 650000,
      accountId: "account-checking-demo",
      categoryId: "category-income-demo",
    },
    {
      id: "report-expense-july-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-07-12",
      description: "Despesas julho demo",
      type: "expense",
      status: "posted",
      amountInCents: 210000,
      accountId: "account-checking-demo",
      categoryId: "category-home-demo",
    },
    {
      id: "report-foreign-tenant",
      tenantId: "tenant-outro",
      financialProfileId: "profile-outro",
      date: "2026-06-10",
      description: "Relatorio de outro contexto",
      type: "expense",
      status: "posted",
      amountInCents: 999999,
      accountId: "account-foreign-demo",
      categoryId: "category-foreign-demo",
    },
  ],
} as const satisfies ReportDataSet;
