import type { FinancialCatalogDataSet } from "./types.js";

export const financialCatalogMockDataSet = {
  context: {
    tenantId: "tenant-demo",
    financialProfileId: "profile-personal-demo",
  },
  accounts: [
    {
      id: "account-checking-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Conta corrente demo",
      type: "checking",
      status: "active",
      balanceInCents: 582250,
      color: "#0F3D4C",
    },
    {
      id: "account-cash-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Carteira demo",
      type: "cash",
      status: "archived",
      balanceInCents: 0,
      color: "#16A34A",
    },
    {
      id: "account-foreign-tenant",
      tenantId: "tenant-outro",
      financialProfileId: "profile-outro",
      name: "Conta de outro contexto",
      type: "checking",
      status: "active",
      balanceInCents: 999999,
    },
  ],
  cards: [
    {
      id: "card-credit-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      nickname: "Cartao principal demo",
      type: "credit",
      status: "active",
      issuerName: "Banco Demo",
      closingDay: 10,
      dueDay: 17,
      lastFourDigits: "1234",
    },
    {
      id: "card-benefit-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      nickname: "Beneficio demo",
      type: "benefit",
      status: "archived",
      issuerName: "Vale Demo",
      lastFourDigits: "9876",
    },
  ],
  categories: [
    {
      id: "category-income-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Receitas",
      type: "income",
      status: "active",
      color: "#16A34A",
      isSystem: true,
      linkedEntriesCount: 2,
    },
    {
      id: "category-food-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Alimentacao",
      type: "expense",
      status: "active",
      color: "#F59E0B",
      linkedEntriesCount: 1,
    },
    {
      id: "category-old-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      name: "Categoria antiga demo",
      type: "expense",
      status: "archived",
      linkedEntriesCount: 0,
    },
  ],
} as const satisfies FinancialCatalogDataSet;
