import type { TransactionDataSet } from "./types.js";

export const transactionMockDataSet = {
  context: {
    tenantId: "tenant-demo",
    financialProfileId: "profile-personal-demo",
  },
  filters: {
    startsOn: "2026-06-01",
    endsOn: "2026-06-30",
  },
  transactions: [
    {
      id: "transaction-income-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-05",
      description: "Receita mensal demo",
      type: "income",
      status: "posted",
      amountInCents: 620000,
      accountId: "account-checking-demo",
      categoryId: "category-income-demo",
    },
    {
      id: "transaction-market-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-09",
      description: "Mercado demo",
      type: "expense",
      status: "posted",
      amountInCents: 95000,
      accountId: "account-checking-demo",
      categoryId: "category-food-demo",
    },
    {
      id: "transaction-transfer-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-11",
      description: "Reserva demo",
      type: "transfer",
      status: "posted",
      amountInCents: 50000,
      accountId: "account-checking-demo",
      destinationAccountId: "account-savings-demo",
    },
    {
      id: "transaction-card-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-16",
      description: "Fatura demo",
      type: "expense",
      status: "scheduled",
      amountInCents: 62750,
      accountId: "account-checking-demo",
      categoryId: "category-card-demo",
    },
    {
      id: "transaction-archived-demo",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      date: "2026-06-02",
      description: "Lancamento arquivado demo",
      type: "expense",
      status: "archived",
      amountInCents: 1200,
      accountId: "account-checking-demo",
      categoryId: "category-old-demo",
    },
    {
      id: "transaction-foreign-tenant",
      tenantId: "tenant-outro",
      financialProfileId: "profile-outro",
      date: "2026-06-10",
      description: "Lancamento de outro contexto",
      type: "expense",
      status: "posted",
      amountInCents: 999999,
      accountId: "account-foreign-demo",
    },
  ],
} as const satisfies TransactionDataSet;
