import { sharedShellStyles } from "../shared-styles.js";

export function accountsCardsPageStyles(): string {
  return `
    ${sharedShellStyles()}
    main { display: grid; gap: 14px; margin: 0 auto; max-width: 1440px; padding: 18px 20px; width: 100%; }
    .master-heading { align-items: center; display: flex; gap: 12px; justify-content: space-between; } .master-heading > div:first-child { display: grid; gap: 4px; max-width: 720px; } .master-actions { display: flex; flex-wrap: wrap; gap: 8px; }
    .master-toolbar, .master-panel { background: var(--surface); border: 1px solid var(--line); border-radius: var(--radius-lg); box-shadow: var(--shadow-sm); display: grid; gap: 12px; padding: 14px; }
    [hidden] { display: none !important; }
    .tab-list { background: var(--surface-soft); border: 1px solid #d8e7ec; border-radius: var(--radius); display: flex; gap: 4px; padding: 4px; } .tab-button { background: transparent; color: var(--primary); flex: 1 1 0; font-size: 0.8125rem; gap: 6px; min-height: 30px; min-width: 0; padding: 0 10px; } .tab-button[aria-selected="true"] { background: var(--surface); border: 1px solid #d4e6ec; color: var(--text); font-weight: 600; } .tab-button span, .section-heading > span, .status-pill, .dialog-subsection-heading > span { background: var(--primary-soft); border-radius: 999px; color: var(--primary); font-size: 0.6875rem; font-weight: 700; padding: 2px 7px; white-space: nowrap; }
    .filter-row { display: grid; gap: 10px; grid-template-columns: minmax(0, 1fr) minmax(10rem, .22fr); }
    .section-heading { align-items: center; display: flex; gap: 10px; justify-content: space-between; } .section-heading > div { display: grid; gap: 3px; }
    .master-list { display: grid; gap: 0; } .master-item { align-items: start; border-top: 1px solid var(--line); display: grid; gap: 12px; grid-template-columns: 36px minmax(0, 1fr) minmax(8rem, auto) auto; padding: 10px 0; } .master-item:first-child { border-top: 0; padding-top: 0; }
    .identity-mark { align-items: center; background: var(--primary-soft); border: 1px solid #d4e6ec; border-radius: 8px; color: white; display: flex; height: 36px; justify-content: center; overflow: hidden; width: 36px; } .card-mark { background: #f8fafc; }
    .brand-icon { display: block; height: 36px; width: 36px; } .card-brand-icon { filter: drop-shadow(0 1px 2px rgba(15,23,42,.14)); }
    .brand-icon-wrap { align-items: center; background: #fff; display: flex; height: 36px; justify-content: center; width: 36px; } .institution-logo-img { background: #fff; border-radius: 7px; object-fit: contain; padding: 4px; }
    .item-main { display: grid; gap: 3px; min-width: 0; } .item-main p { color: var(--muted); font-size: 0.8125rem; line-height: 1.4; } .item-title-row { align-items: center; display: flex; flex-wrap: wrap; gap: 6px; } .amount-stack { display: grid; gap: 2px; justify-items: end; text-align: right; white-space: nowrap; } .amount-stack span { color: var(--muted); font-size: 0.6875rem; font-weight: 700; text-transform: uppercase; } .amount-stack strong { color: var(--text); font-size: 0.875rem; }
    .instrument-list { border: 1px solid var(--line); border-radius: var(--radius); display: grid; gap: 0; margin-top: 6px; overflow: hidden; } .instrument-list.is-empty { padding: 8px 10px; font-size: 0.8125rem; color: var(--muted); }
    .instrument-warning { background: var(--danger-bg); border: 1px solid #fecaca; border-radius: var(--radius); color: var(--danger); font-size: 0.8125rem; font-weight: 600; margin-top: 6px; padding: 7px 10px; }
    .instrument-item { align-items: center; background: var(--surface-soft); border-top: 1px solid var(--line); display: grid; gap: 8px; grid-template-columns: minmax(0, 1fr) auto; padding: 8px 10px; } .instrument-item:first-child { border-top: 0; } .instrument-meta { font-size: 0.8125rem; }
    .instrument-side { display: grid; gap: 6px; justify-items: end; } .instrument-tags { display: flex; flex-wrap: wrap; gap: 4px; justify-content: flex-end; } .instrument-pill { background: #e0f2fe; border-radius: 999px; color: #075985; font-size: 0.6875rem; font-weight: 700; padding: 2px 7px; white-space: nowrap; } .instrument-pill.is-archived { background: #f1f5f9; color: #475569; }
    .instrument-actions { display: flex; gap: 4px; justify-content: flex-end; }
    .item-actions { display: flex; gap: 6px; justify-content: flex-end; } .inline-action-form { display: block; gap: 0; } .icon-button { background: var(--surface); border: 1px solid var(--line); border-radius: var(--radius); color: var(--primary); min-height: 28px; padding: 0; width: 28px; transition: background 120ms ease-out, border-color 120ms ease-out, color 120ms ease-out; } .icon-button:hover { background: var(--primary-soft); border-color: #c8dde5; } .danger-icon-button { color: var(--muted); } .danger-icon-button:hover { background: var(--danger-bg); border-color: #fecaca; color: var(--danger); } .action-icon { display: block; height: 14px; width: 14px; }
    .edit-grid { display: grid; gap: 10px; grid-template-columns: repeat(3, minmax(0, 1fr)); margin-top: 10px; } .edit-grid button, .edit-grid .form-status, .edit-grid .legacy-account-identifier { grid-column: 1 / -1; } .legacy-account-identifier { margin: 0; }
    .dialog-subsection { border-top: 1px solid var(--line); display: grid; gap: 10px; margin-top: 14px; padding-top: 14px; } .dialog-subsection-heading { align-items: center; display: flex; gap: 10px; justify-content: space-between; } .dialog-subsection-heading > div { display: grid; gap: 3px; } .dialog-subsection h3 { font-size: 0.875rem; margin: 0; } .dialog-instrument-forms { display: grid; gap: 10px; } .instrument-edit-form { background: var(--surface-soft); border: 1px solid var(--line); border-radius: var(--radius); margin-top: 0; padding: 10px; } .instrument-edit-heading { align-items: center; display: flex; gap: 8px; grid-column: 1 / -1; justify-content: space-between; }
    .filter-empty-state { margin-top: 4px; }
    .master-dialog { border: 1px solid var(--line); border-radius: var(--radius-lg); box-shadow: 0 24px 80px rgba(15,23,42,.18); max-width: 720px; padding: 18px; width: calc(100% - 32px); } .master-dialog::backdrop { background: rgba(15,23,42,.42); } .dialog-close-form { display: flex; justify-content: flex-end; margin-bottom: 10px; } .dialog-heading { display: grid; gap: 3px; }
    @media (max-width: 900px) { .edit-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } .master-heading { align-items: stretch; display: grid; } .master-item { grid-template-columns: 36px minmax(0, 1fr) auto; } .item-actions { grid-column: 2 / -1; justify-content: flex-start; } }
    @media (max-width: 760px) { .tab-list, .master-actions { display: grid; } .filter-row, .edit-grid, .master-item, .section-heading, .instrument-item, .dialog-subsection-heading, .instrument-edit-heading { display: grid; grid-template-columns: 1fr; } .item-actions { grid-column: auto; justify-content: flex-start; } .instrument-side { justify-items: start; } .instrument-tags, .instrument-actions { justify-content: flex-start; } .amount-stack { justify-items: start; text-align: left; white-space: normal; } }
  `;
}
