import type { DashboardDataSet } from "./types.js";

export const dashboardMockDataSet = {
  context: {
    tenantId: "tenant-demo",
    financialProfileId: "profile-personal-demo",
  },
  period: {
    startsOn: "2026-06-01",
    endsOn: "2026-06-30",
    label: "Junho de 2026",
  },
  openingBalanceInCents: 240000,
  entries: [
    {
      id: "entry-income-salary",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      postedOn: "2026-06-05",
      description: "Receita mensal demo",
      type: "income",
      status: "posted",
      amountInCents: 620000,
      categoryName: "Receitas",
    },
    {
      id: "entry-income-service",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      postedOn: "2026-06-12",
      description: "Servico eventual demo",
      type: "income",
      status: "posted",
      amountInCents: 80000,
      categoryName: "Receitas",
    },
    {
      id: "entry-expense-home",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      postedOn: "2026-06-07",
      description: "Moradia demo",
      type: "expense",
      status: "posted",
      amountInCents: 180000,
      categoryName: "Moradia",
    },
    {
      id: "entry-expense-market",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      postedOn: "2026-06-09",
      description: "Mercado demo",
      type: "expense",
      status: "posted",
      amountInCents: 95000,
      categoryName: "Alimentacao",
    },
    {
      id: "entry-expense-card",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      postedOn: "2026-06-15",
      description: "Fatura demo",
      type: "expense",
      status: "scheduled",
      amountInCents: 62750,
      categoryName: "Cartao",
    },
    {
      id: "entry-foreign-tenant",
      tenantId: "tenant-outro",
      financialProfileId: "profile-outro",
      postedOn: "2026-06-10",
      description: "Dado de outro contexto que deve ser ignorado",
      type: "expense",
      status: "posted",
      amountInCents: 999999,
      categoryName: "Ignorar",
    },
  ],
  upcomingBills: [
    {
      id: "bill-energy",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      dueOn: "2026-06-18",
      description: "Energia demo",
      amountInCents: 22400,
      status: "open",
    },
    {
      id: "bill-subscription",
      tenantId: "tenant-demo",
      financialProfileId: "profile-personal-demo",
      dueOn: "2026-06-21",
      description: "Assinatura demo",
      amountInCents: 3900,
      status: "open",
    },
  ],
  dailyAvailability: {
    availableTodayInCents: 14320,
    currency: "BRL",
    confidence: "low",
    calculatedAt: "2026-06-16T12:00:00.000Z",
    detailPath: "/app/revisao/disponibilidade",
    assumptions: [
      "Saldo atual e fatura demo foram considerados.",
      "Recorrencias estatisticas ainda dependem de revisao.",
    ],
    limitations: ["Historico insuficiente para alta confianca neste perfil demo."],
  },
} as const satisfies DashboardDataSet;
